// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file news.proto (package news.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_struct } from "@bufbuild/protobuf/wkt";
import type { JsonObject, Message } from "@bufbuild/protobuf";

/**
 * Describes the file news.proto.
 */
export const file_news: GenFile = /*@__PURE__*/
  fileDesc("CgpuZXdzLnByb3RvEgduZXdzLnYxIroBCgxOZXdzQW5hbHl6ZWQSHwoGc291cmNlGAEgASgLMg8ubmV3cy52MS5Tb3VyY2USDQoFdGl0bGUYAiABKAkSDwoHY29udGVudBgDIAEoCRIUCgxwdWJsaXNoZWRfYXQYBCABKAMSEwoLaW5nZXN0ZWRfYXQYBSABKAMSEwoLcHJlcGFyZWRfYXQYBiABKAMSKQoIYW5hbHlzaXMYByABKAsyFy5nb29nbGUucHJvdG9idWYuU3RydWN0IisKBlNvdXJjZRIMCgRuYW1lGAEgASgJEhMKC2NyZWRpYmlsaXR5GAIgASgCYgZwcm90bzM", [file_google_protobuf_struct]);

/**
 * @generated from message news.v1.NewsAnalyzed
 */
export type NewsAnalyzed = Message<"news.v1.NewsAnalyzed"> & {
  /**
   * @generated from field: news.v1.Source source = 1;
   */
  source?: Source;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: string content = 3;
   */
  content: string;

  /**
   * @generated from field: int64 published_at = 4;
   */
  publishedAt: bigint;

  /**
   * @generated from field: int64 ingested_at = 5;
   */
  ingestedAt: bigint;

  /**
   * @generated from field: int64 prepared_at = 6;
   */
  preparedAt: bigint;

  /**
   * @generated from field: google.protobuf.Struct analysis = 7;
   */
  analysis?: JsonObject;
};

/**
 * Describes the message news.v1.NewsAnalyzed.
 * Use `create(NewsAnalyzedSchema)` to create a new message.
 */
export const NewsAnalyzedSchema: GenMessage<NewsAnalyzed> = /*@__PURE__*/
  messageDesc(file_news, 0);

/**
 * @generated from message news.v1.Source
 */
export type Source = Message<"news.v1.Source"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: float credibility = 2;
   */
  credibility: number;
};

/**
 * Describes the message news.v1.Source.
 * Use `create(SourceSchema)` to create a new message.
 */
export const SourceSchema: GenMessage<Source> = /*@__PURE__*/
  messageDesc(file_news, 1);

